version: "3.1"
services:
  web-server:
    build: .
    env_file:
      - ./envs/test.env
    ports:
      - "5000:5000"

  mongodb:
    image: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
      MONGO_INITDB_DATABASE: test
